language: cpp

# we need a newer cmake
dist: trusty
sudo: required

compiler:
    - clang
    - gcc

matrix:
    allow_failures:
        # FIXME: what the hell is going on here?
      - compiler: gcc

env:
    global:
      - DYNINST=DyninstAPI-9.1.0
      - DYNINSTAPI_RT_LIB=$HOME/dyninst/lib/libdyninstAPI_RT.so
      - LD_LIBRARY_PATH=$HOME/dyninst/lib

cache:
    apt: true
    directories:
        - $HOME/dyninst

before_install:
    - sudo apt-get -qq update
    - sudo apt-get -y install libiberty-dev libboost-all-dev libelf-dev
    - test -d $HOME/dyninst/include || wget -N http://www.paradyn.org/release9.1.0/$DYNINST.tgz
    - test -d $HOME/dyninst/include || tar xf $DYNINST.tgz

install:
    - test -d $HOME/dyninst/include || cmake . -DCMAKE_INSTALL_PREFIX=$HOME/dyninst -DCMAKE_C_COMPILER=gcc
      -DCMAKE_CXX_COMPILER=g++ -DCMAKE_CXX_FLAGS="-D_GLIBCXX_USE_CXX11_ABI=0" -DUSE_GNU_DEMANGLER=1
    - test -d $HOME/dyninst/include || make -j`nproc` install

script:
    - CXXFLAGS="-Werror -isystem $HOME/dyninst/include" LDFLAGS="-L$HOME/dyninst/lib" make test run
