language: cpp
sudo: false
compiler:
    - clang
    - gcc
env:
    - DYNINST=DyninstAPI-9.1.0
cache:
    directories:
        - $HOME/dyninst
before_install:
    - test -d $HOME/dyninst || wget -N http://www.paradyn.org/release9.1.0/$DYNINST.tgz
    - test -d $HOME/dyninst || tar xf $DYNINST.tgz
install:
    - test -d $HOME/dyninst || (mkdir -p $DYNINST/work && cd $DYNINST/work && cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/dyninst)
    - test -d $HOME/dyninst || make -C $DYNINST/work install
script:
    - make
    - make test
